### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Vuurvos1** [RowinRuizendaal/Blauwe-maan#1]
_**Mike**_ maak nou eens dat design af, dan kunnen we door. Wakka man
![Alt Text](https://media.giphy.com/media/1fo53TVAlP81MYBSUg/giphy-downsized.gif)
Nu jij nog...

**Comment by mikehov** [comment]
Klaar

**Comment by Vuurvos1** [comment]
Design preview: https://xd.adobe.com/view/a49f2979-7a10-49cd-9fdf-064bde58b5a7-f1cc/

**Comment by RowinRuizendaal** [comment]
Add the asset files or links where we can find them please.

Thanks

**Comment by RowinRuizendaal** [comment]
@mikehov

**Comment by RowinRuizendaal** [comment]
Also what about the slug of the projects? If I click on the 'discover' project what will appear? How does this slug look like?

**Comment by mikehov** [comment]
Assets has been uploaded to the discord channel.
