### ISSUE TITLE
Svelte Kit Setup

### ISSUE THREAD

**Issue by Vuurvos1** [RowinRuizendaal/Blauwe-maan#2]
Setup Svelte kit template

Please don't break anything public beta 🙏

**Comment by RowinRuizendaal** [comment]
status? :)

**Comment by Vuurvos1** [comment]
Svelte kit is still in public beta, check progress towards v1.0 [here](https://github.com/sveltejs/kit/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0) also waiting on  issue #1
